# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yzapp', '0002_auto_20180103_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
