# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-04 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yzapp', '0003_auto_20180103_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
