# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-04 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yzapp', '0004_auto_20180104_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
