# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yzapp', '0007_auto_20180106_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to='img'),
        ),
    ]
