# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yzapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='path',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default='', null=True),
        ),
    ]
