# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yzapp', '0005_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
